const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1564222784000,
      duration: 10800000,
      id: 'sqlrfrybcjbkb',
      name: 'Repair Café Schwabing',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591531200000,
      local_date: '2020-06-07',
      local_time: '14:00',
      updated: 1564222784000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26538112,
        name: 'Seidlvilla',
        lat: 48.15855026245117,
        lon: 11.587692260742188,
        repinned: false,
        address_1: 'Nikolaiplatz 1b',
        city: 'München ',
        country: 'DE',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1490371801000,
        name: 'Repair Café Meetup',
        id: 22994509,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Repair-Cafe-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Repair-Cafe-Meetup/events/sqlrfrybcjbkb/',
      description: '<p>Jeden ersten Sonntag ab 14 Uhr bis 17 Uhr finde in der Seidlvilla in Schwabing unser Repair Café statt. Bringt Eure kaputten Uhren, Elektro Kleinteile, Haushaltsgeräte, Kleidungsstücke, Taschen, Textilien sowie Laptops oder Handys die repariert werden müssen. Wenn ihr selbst wisst, wie es geht, und mitmachen wollt, freuen wir uns auf deine Mithilfe bei reparieren hierzu bitte vorab melden unter [masked]. </p> <p>Every first Sunday from 2pm to 5pm the Repair Café Schwabing takes place in the Seidlvilla in Schwabing (U3 and 6 Münchner Freiheit). Bring your broken watches, electronic items, household items, clothes, bags and other textiles as well as laptops and phones. If you know how to repair and want to join in, we are looking forward to your contribution. Please let us know in advance, if you will be part of the repair team: [masked] and we will give you further information.</p> ',
      how_to_find_us: 'zwischen Münchner Freiheit und Giselastraße',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: 'lkgknpybchbdc',
      name: 'Deutsch-Japanischer\u00ad Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1590166800000,
      local_date: '2020-05-22',
      local_time: '19:00',
      updated: 1522694856000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1512221367000,
        name: 'Deutsch-Japanischer Stammtisch',
        id: 26763059,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'deutsch-japanischer-stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybchbdc/',
      description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1574974495000,
      duration: 10800000,
      fee: {
        accepts: 'paypal',
        amount: 15,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: true,
      },
      id: '266813030',
      name: 'Agile Game Night #42 - Murmelbahnspiel',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594917000000,
      local_date: '2020-07-16',
      local_time: '18:30',
      updated: 1582196146000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1471362725000,
        name: 'Agile Game Nights',
        id: 20321716,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Agile-Game-Night',
        who: 'Agile Gamer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Agile-Game-Night/events/266813030/',
      description: '<p>Michael Cramer ist wieder mal bei uns und präsentiert das Murmelbahnspiel.</p> <p>Bei Marble Scrummer können mehrere Gruppen beim Bau einer LEGO-Kugelbahn in 90 Minuten verschiedene Scrum Bestandteile hautnah erleben, wie Backlogs, Sprint-Zyklen, Retrospektiven, Skalierung und Definition of Done. Die typischen Integrations- und Kommunikationsprobleme des Scrum-Alltags treten auch bei dieser Übung zuverlässig auf, zumal hier im Gegensatz zu den üblichen LEGO-Simulationsspielen nach jeder Iteration tatsächlich ein lauffähiges Inkrement erstellt und getestet werden kann. Daher eignet sich Marble Scrummer besonders als zusammenfassende Abschluss-Simulation in Scrum- oder Less-Trainings.</p> <p>Michael Cramer über sich: Passion for Projects and People - Agile Coach, Trainer, Facilitator. Die Webseite',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '19:30',
      local_date: '2020-04-28',
      link: 'https://www.meetup.com/meetup-group-iGKmHUcY/events/nqrfmqybcgblc/',
      visibility: 'public_limited',
      group: {
        created: 1542636787000,
        name: 'Food Addicts in Recovery Anonymous',
        id: 30556809,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'meetup-group-iGKmHUcY',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 1,
      duration: 5400000,
      time: 1588095000000,
      utc_offset: 7200000,
      name: 'Food Addicts in Recovery Anonymous (FA)',
      id: 'nqrfmqybcgblc',
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: 'lkgknpybcjbjc',
      name: 'Deutsch-Japanischer\u00ad Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593190800000,
      local_date: '2020-06-26',
      local_time: '19:00',
      updated: 1522694856000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1512221367000,
        name: 'Deutsch-Japanischer Stammtisch',
        id: 26763059,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'deutsch-japanischer-stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcjbjc/',
      description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1515261128000,
      duration: 5400000,
      id: 'jxdbfpybcgblc',
      name: 'Soirée “prise de parole en public“ ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588095000000,
      local_date: '2020-04-28',
      local_time: '19:30',
      updated: 1515261129000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1470589277000,
        name: 'München Französische Sprache Meetup',
        id: 20289414,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Franzosische-Sprache-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munchen-Franzosische-Sprache-Meetup/events/jxdbfpybcgblc/',
      description: 'test',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1584796605000,
      duration: 4500000,
      id: 'pzfxqrybcgblc',
      name: 'Vinyasa Yoga Online!',
      rsvp_limit: 30,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588093200000,
      local_date: '2020-04-28',
      local_time: '19:00',
      updated: 1584796605000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25883905,
        name: 'Doina Yoga @Heilpraxisgemeinschaft',
        lat: 48.12617874145508,
        lon: 11.549954414367676,
        repinned: true,
        address_1: 'Grimmstraße 1',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1531374419000,
        name: 'Yoga Doina',
        id: 29215079,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Yoga-mit-Doina',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Yoga-mit-Doina/events/pzfxqrybcgblc/',
      description: '<p>Aufgrund der aktuellen Gesundheitslage biete ich euch live Onlinekurse!</p> <p>Vinyasa Yoga ist eine dynamische Yogaform, bei welcher Achtsamkeit, Energie, Ruhe und Kraft zusammenkommen. Als Hatha Vinyasa- &amp; Kundalini Yoga Lehrerin bringe ich in meinen Stunden verschiedene Einflüsse zusammen. Es geht um Erdung, sich selbst wahrnehmen, körperliche wie auch geistige Kräftigung, das Lösen von Blockaden und Loslassen von allem, was einem nicht mehr dient. Um dann letztendlich sich selbst etwas näher zu kommen und sein Potential zu entfalten. Ich wende physische und energetische Techniken an und arbeite mit Chakren, um ein noch tieferes Erlebnis zu ermöglichen.</p> <p>Im zweiten Teil der Klasse werden wir einfache Meditationstechniken anwenden, um gerade in diesen Zeiten Ruhe zu bewahren, damit unsere Selbstheilungskräfte aktiviert werden können.</p> <p>Die Stunde ist für alle Level geeignet!</p> <p>Anmeldung: ',
      how_to_find_us: '3 Etage, rechts. Türe unten ist offen, wenn nicht bei Heilpraxis Kern klingeln.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1586186779000,
      duration: 7200000,
      id: '269891185',
      name: 'IBM Masterclass & Hackathon: AI Explainability',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588316400000,
      local_date: '2020-05-01',
      local_time: '09:00',
      updated: 1586186779000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 32,
      is_online_event: false,
      group: {
        created: 1400181332000,
        name: 'Big Data Developers in Munich',
        id: 14476282,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Big-Data-Developers-in-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/269891185/',
      description: '<p>Go beyond the code, advance towards responsible and trustworthy AI. Begins March 27, 2020 and ends May 1, 2020. This is a free on-line webinar that can be accessed at any time.</p> <p>REGISTER HERE FOR THIS FREE COURSE &amp; EVENT: ibm.biz/AIExplainability</p> <p>Take our free masterclass and then apply your new skills in the online Hackathon. Come learn new open-source and IBM data science tools like AIX360 and Lale. As well as, how to explain your model to any stakeholder and how to integrate explainable workflows.</p> <p>MASTERCLASS<br/>Quickly learn new data science concepts with this free 90-minute micro-course.</p> <p>HACKATHON<br/>Apply these new concepts by creating your own project to showcase and compete for the $8,000 prizepool and an IBM skill badge.</p> <p>MENTORSHIP<br/>Connect 1:1 with IBM data science experts for help and guidance on your project.</p> <p>WHO IS THIS FOR?<br/>All Data Scientists, AI &amp; ML Devs and Engineers, Startups and Enterprise</p> <p>WHY EXPLAINABILITY?<br/>Explainability is the ability for data scientists to produce applicable results for their peers, managers, and end-users. Can your results be understood and applied by other data scientists and stakeholders? It is up to you as a data scientist to use your business knowledge, mathematical, and programmatic skills to communicate your findings and methods. Explainability is an important tool used to make your reasoning behind each decision transparent and repeatable.</p> <p>In this course, learn the importance of building an explainability workflow and how to implement these practices from the beginning. Then, using your new skills and tools, apply what you have learned by submitting your own project. Each submission for the hackathon will have a chance at cash prizes during the 6-week competition.<br/>-------------------------------------------------</p> <p>REGISTER HERE FOR THIS FREE COURSE &amp; EVENT: ibm.biz/AIExplainability</p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1586076990000,
      duration: 3600000,
      id: 'fmphrrybcgblc',
      name: 'Online Meditation',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588095000000,
      local_date: '2020-04-28',
      local_time: '19:30',
      updated: 1586076990000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1517207017000,
        name: 'Meditation - Jeder kann meditieren',
        id: 27311269,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Meditation-Jeder-kann-meditieren',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Meditation-Jeder-kann-meditieren/events/fmphrrybcgblc/',
      description: '<p>Bitte melde dich an:<br/>.<br/>Tauch ab in das Feld der Möglichkeiten...<br/>.<br/>Gerade JETZT in dieser ungewissen Zeit ist es essentiell sich selbst innere Ressourcen zu erschaffen für Klarheit, Gesundheit und Führung. Kontrollierst du dein Inneres, bestimmst du wer du BIST.<br/>.<br/>Hebe mit einfachen Qigong Vorübungen dein Energielevel und öffne die Energiekänale in deinem Körper für eine starke Gesundheit. Lerne Schritt für Schritt dein Herz und deinen Geist in Harmonie zu bringen. Erschaffe dir die Möglichkeit zu sein wer du sein willst.<br/>.<br/>Mach es dir zu Hause gemütlich und lass uns zusammen abtauchen...<br/>.<br/>Was du lernen kannst:<br/>-deinen Geist zu kontrollieren<br/>-dein Herz zu öffnen<br/>-Emotionen zu besänftigen<br/>-Kontakt zur Intuition aufzubauen<br/>-deine Gesundheit zu stärken<br/>.<br/>Der Kurs ist für dich, wenn du interessiert bist an:<br/>-Veränderung aus dem Inneren zu bewirken<br/>-Antworten aus deinem Inneren zu erhalten<br/>-einer Meditationsgemeinschaft<br/>-Kontakt zu deiner Intuition aufzubauen<br/>-vieles mehr...<br/>.<br/>Ablauf:<br/>1) Qigong Aufwärmübungen<br/>2) geführte Meditation<br/>3) Austausch ( open end )</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1585859254000,
      duration: 5400000,
      id: 'rhmgrrybchbhb',
      name: 'Chinese/ German Club in Munich',
      rsvp_limit: 13,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588698000000,
      local_date: '2020-05-05',
      local_time: '19:00',
      updated: 1587584062000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26903444,
        name: 'Online',
        lat: 48.13512420654297,
        lon: 11.58198070526123,
        repinned: false,
        address_1: 'Online Adresse noch nicht verfügbar',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1444592791000,
        name: 'Toastmasters Clubs in and around Munich',
        id: 19017360,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Toastmasters-Clubs-in-and-around-Munich',
        who: 'Toastmaster',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Toastmasters-Clubs-in-and-around-Munich/events/rhmgrrybchbhb/',
      description: '<p>PLEASE NOTE: This meeting will take place online because of the concerns of coronavirus. If you would like to join us, please drop Hongnan a private message. You will receive a link to join the virtual meeting shortly before it takes place.</p> <p>We, several experienced Toastmasters are starting a Chinese/German bilingual Toastmasters Club in Munich and having our regular meetings twice a month: on the second and last Sunday respectively.</p> <p>Everyone who wants to improve his/her public speaking skills in Chinese or German, professionals having cooperation with China and want to get more understanding of the Chinese language and culture, Chinese students learning German, Chinese learners, Chinese food lovers, etc... is most welcome to join us.</p> <p>Also check out our Facebook page: ',
      how_to_find_us: 'PM Hongnan to get an invite',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1532377148000,
      duration: 18000000,
      id: 'jbbfbqybchbjb',
      name: '₿🍻 Monthly Bitcoin Munich Stammtisch — 📺 Virtual Edition',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588780800000,
      local_date: '2020-05-06',
      local_time: '18:00',
      updated: 1587431028000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 26908232,
        name: 'Internet',
        lat: 48.13512420654297,
        lon: 11.58198070526123,
        repinned: true,
        address_1: '—',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1372415991000,
        name: 'Bitcoin Munich',
        id: 9128392,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Bitcoin-Munich',
        who: 'Bitcoiners',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Bitcoin-Munich/events/jbbfbqybchbjb/',
      description: '<p>(English description below.)</p> <p>—</p> <p>Willkommen beim ersten und originalen Stammtisch der Münchner Bitcoin-Enthusiasten!</p> <p>####</p> <p>Aus nachvollziehbaren Gründen treffen wir uns diesmal nur virtuell!</p> <p>Die Idee ist, das informelle, ungezwungene Stammtischformat beizubehalten. Es gibt kein offizielles Programm, schaltet euch einfach rein und plaudert mit! Wie in der physischen Version zielen wir auf eine gute Mischung aus neugierigen Neulingen und Veteranen ab. Zwecks dem lokalen Flair sollte ein Bezug zu München bei euch vorhanden sein.</p> <p>Software: Jitsi Meet (free/libre &amp; open source, self-hosted, kein Logging, keine Registrierung nötig), funktioniert einfach über Browser oder App.</p> <p>Genaue Links und Info siehe unten (Kommentarsektion)!</p> <p>####</p> <p>Wir treffen uns zur zwanglosen Plauderei über die technischen sowie ökonomischen und gesellschaftlichen Aspekte von Bitcoin und anderen Kryptowährungen. Auch werden wir wohl diskutieren, worum es bei dem ganzen Aufruhr um Blockchains eigentlich geht.</p> <p>Egal ob Neulinge oder Profis, ob Urbayer oder Weltbürger, alle sind herzlich willkommen! Ihr könnt immer reichlich interessante Leute treffen, und ihr könnt euch gut für aufregende Projekte zusammenfinden!</p> <p>[...]</p> <p>Dieses informelle Stammtisch-Format findet jeden ersten Mittwoch eines Monats statt und hat keine offiziellen Vorträge oder Präsentationen. Wir setzen weitere Veranstaltungen an zu diesem Zweck an unterschiedlichen Orten. Bitte werft einen Blick auf unsere Übersichtsseite, um diese zu finden.<p>Welcome to the first and original Stammtisch of the Munich Bitcoin enthusiasts!</p> <p>####</p> <p>Due to obvious reasons we\'ll only meet virtually this time.</p> <p>The idea is to keep the informal and easy format of the Stammtisch. There is no official program, just join in and chat with us! Like in the physical version, we\'re aiming for a good mixture of curious newcomers and veterans. For the local flair you should have a reference to Munich.</p> <p>Software: Jitsi Meet (free/libre &amp; open source, self-hosted, no logging, no registration necessary), works simply via browser or app.</p> <p>Exact links and info see below (comment section)!</p> <p>####</p> <p>We meet to casually chat about the technical as well as the economic and societal aspects of Bitcoin and other crypto-currencies. Also we might debate what the fuzz around blockchains is all about.</p> <p>No matter if newbies or pros, if primordial Bavarian or world citizen, everyone is sincerely welcome! You can always meet many interesting people, and you can come together for exciting projects!</p> <p>[...]</p> <p>This informal Stammtisch format takes place every first Wednesday of a month and has no official talks or presentations. We schedule other events for that purpose in various different locations. Please take a closer look at our overview page to find those. ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1582293454000,
      duration: 9000000,
      id: '268882037',
      name: 'Hair - The Musical at Deutsches Theater (In English) ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594143000000,
      local_date: '2020-07-07',
      local_time: '19:30',
      updated: 1582293975000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26758355,
        name: 'Deutsches Theater',
        lat: 48.13722229003906,
        lon: 11.5625,
        repinned: true,
        address_1: 'Schwanthalerstraße 13',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1474457902000,
        name: 'English Improv and Theatre in Munich',
        id: 20450503,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-English-Improv-and-Theatre',
        who: 'English Improv & Theatre Fans',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munich-English-Improv-and-Theatre/events/268882037/',
      description: '<p>HAIR - THE MUSICAL (in English)<br/>[masked] -[masked]</p> <p>MILESTONE OF POP CULTURE<br/>Experience a milestone of pop culture and discover the summer of love once again! No other musical captures the sense of a whole generation better and has brought us songs for all eternity at the same time. After a celebrated first guest performance in Cologne within the 50th anniversary tour, Hair is now coming to Munich.</p> <p>LET THE SUNSHINE IN<br/>Welcome to the „Age of Aquarius“: The year is 1967 and the Hippie youth in the East Village of New York City fights against the establishment – with long hair, flower power and loads of music. Set against the political backdrop of the late 60s, Hair – The Musical celebrates life and love with its Grammy-awarded soundtrack and hits like „Aquarius“ and „Let The Sunshine In“.</p> <p>DELIGHTFUL JOURNEY THROUGH TIME<br/>Wild, colourful and free – the legendary Hippie musical has lost none of its energy. In London, the young and successful production, performed entirely in English, won a What’s On Stage Award. „A bright new dawn for the Age of Aquarius“, exults the Guardian. Bild in Cologne proclaims: „A delightful journey through time full of emotion“.</p> <p>TRAILER: ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1581065421000,
      duration: 143940000,
      id: '268530677',
      name: 'OUTDOOR COWORKING 2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593151200000,
      local_date: '2020-06-26',
      local_time: '08:00',
      updated: 1581065462000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1442238396000,
        name: 'OUTDOOR COWORKING',
        id: 18930367,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'outdoor-coworking-day',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/outdoor-coworking-day/events/268530677/',
      description: '<p>Coworking mal ganz woanders, aber doch im eigenen Van. Mit ganz wem anders, aber doch unter Freunden. Lüftet mit bekannten Unternehmen, Vanlifeworkern und spannenden Personen den Büroalltag mal ordentlich durch. 2019 waren von Firmen wie SIXT, ReCup, andere aus der Sport- oder Automotive-Branche, bis hin zu Agenturen, Freelancern, Fotografen und Influencern alles dabei.<br/>Wir laden Euch ein, Teil unseres #woooday in der Natur zu sein.</p> <p>Buchung unter: www.outdoor-coworking-day.de</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1574974457000,
      duration: 10800000,
      fee: {
        accepts: 'paypal',
        amount: 15,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: true,
      },
      id: '266812945',
      name: 'Agile Game Night #41 - Lego Serious Play',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592929800000,
      local_date: '2020-06-23',
      local_time: '18:30',
      rsvp_close_offset: 'PT24H',
      updated: 1582196479000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1471362725000,
        name: 'Agile Game Nights',
        id: 20321716,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Agile-Game-Night',
        who: 'Agile Gamer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Agile-Game-Night/events/266812945/',
      description: '<p>Wir spielen wieder mal Lego Serious Play.<br/>Sybille Kuwert wird durch den Abend führen.<br/>Achtung: Max. 12 Teilnehmer.</p> <p>Wenn wir LEGO® Serious Play ® hören, denken wir an die LEGO Steine, mit denen wir so gerne als Kinder gespielt haben und fragen uns, was das im beruflichen Alltag zu suchen hat.</p> <p>Auch wenn die Steine von LEGO® Serious Play ®, denen aus unserer Kindheit ähneln, werden sie eingesetzt, um in einem kreativen Prozess, Wissen frei zu setzen, Denkmuster aufzubrechen und Kommunikation zu fokussieren.</p> <p>Wer LEGO® Serious Play ® kennen lernen und ausprobieren möchte, der sollte sich diesen Abend vormerken.<br/>Ihr werdet mit den Steinen verschiedene Aufgaben lösen und mit viel Spaß die verschiedenen Einsatzmöglichkeiten von LEGO® Serious Play ® erleben.</p> <p>Sybille Kuwert (certified LEGO® Serious Play ® facilitator) diskutiert mit Euch die Chancen und Grenzen der Methode.</p> <p>Die Anzahl der Teilnehmer ist auf 12 begrenzt.</p> <p>Happy Gaming<br/>Ellen und Sieglinde</p> <p>PS: Du hast auch ein tolles Spiel und möchtest uns das gern zeigen oder auch ausprobieren? Gastmoderatoren sind herzlich eingeladen. Sprich uns an.<br/>----------------------------<br/>Die Agile Game Night ist die Experimentierplattform für Business-Spiele</p> <p>Alle Übungen und Spiele können in Trainings, Workshops, aber auch Scrum-Retrospektiven oder anderen agilen Meetings genutzt werden, im Team neue Lösungsansätze zu entwickeln und Erfahrungen erlebbar zu machen. Unsere Game Night ist für jeden gedacht, der mehr über Agile Methoden erfahren und dabei Spaß haben und spielen möchte. Darüber hinaus können auch Trainer und Coaches davon profitieren, wie sie Spiele in ihre Seminare einbinden und diese vorab schon mal ausprobieren können.</p> <p>Spiele bilden metaphorisch reales Leben ab und helfen, Strukturen nicht nur theoretisch, sondern persönlich zu erleben, erfahren und verinnerlichen.</p> <p>Teilen Sie die Veranstaltung und laden Sie andere ein:</p> <p>',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1584390789000,
      duration: 14400000,
      id: '269466520',
      name: '2. agiles PM-Trendforum 2020 (digital) am 07.05.2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588867200000,
      local_date: '2020-05-07',
      local_time: '18:00',
      updated: 1587463072000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 76,
      is_online_event: false,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466520/',
      description: '<p>MS-Teams Meeting (see Online Link here)</p> <p><p>Agenda:</p> <p>18:00 Uhr – Begrüßung, Einleitung, Infos zum Ablauf</p> <p>18:15 Uhr – Vortrag 1: -&gt; „Office 365 – Implementierung für das Arbeiten im Homeoffice: Weitere nachhaltige O365 Erweiterungen für die Bereiche Ideenmanagement, Business Cases und Projektkollaboration mit der Edison 365 IT-Suite</p> <p>Vortrag Herr Andreas Hock, Partner 3Pworx GmbH</p> <p>Aufgrund der derzeitigen Corona Krise sind gut ausgebaute und werthaltige Cloud- und Homeoffice Lösungen in aller Munde. Das Arbeiten von zu Hause aus soll vor allem Spaß machen und auch aus der Sicht der Produktivität ein hohes Zielmaß erreichen.</p> <p>Eine der führenden Lösungen, um effizient und professionell vom Homeoffice aus arbeitsfähig zu sein ist Office 365.</p> <p>Office 365 bietet vor allem interessante Lösungen und Apps aus dem Bereich der digitalen Zusammenarbeit, wie MS Teams, SharePoint, usw. Agile Methoden werden ebenfalls reichlich unterstützt.</p> <p>Dieses vorhandene Toolpaket kann durch Lösungen aus dem Bereich Ideenmanagement, Business Cases und Projekt-Kollaboration mit den fertigen Edison 365 Produktlösungen intelligent und nachhaltig erweitert werden.</p> <p>Die nahtlose Integration ins Office 365 Umfeld ist sehr einfach darstellbar. Weitere Schnittstellen zu MS Teams, usw. sind schlüsselfertig.</p> <p>Einen ersten Überblick der Produkte finden Sie hier: <p>19:15 Uhr – Vortrag 2: „Orthogonales Projektmanagement – Nicht planen, nicht vereinbaren, sondern entscheiden lassen</p> <p>Vortrag von Herrn Daniel Juling</p> <p>Weder die Modelle des klassischen PM, noch die Modelle des agilen PM sind ausreichend geeignet, um die Entscheidungsintelligenz der Evolution zu nutzen. Mit dem orthogonalen Denken eröffnen Sie sich eine Methode, die immense Skalierungseffekte zulässt, indem Sie bewusst Entscheidungen an den Markt delegieren und in Ihre Projekte einbinden.</p> <p>Lernen Sie das orthogonale PM kennen und erweitern Sie Ihre Methoden-Kiste um ein machtvolles Werkzeug.</p> <p>20:15 Uhr – Vortrag 3: „Projektmanagement Trainings vor dem Wandel der Zeit. Agil – Klassisch – Hybrid | Präsenztrainings – Online Trainings</p> <p>Vortrag von Herrn Andreas Hock, Partner 3Pworx GmbH und Herrn Helmut Schneider, CPS Consulting</p> <p>Die ganze Welt steht derzeit vor nie da gewesenen Veränderungen. Was gestern noch gültig war hat morgen vielleicht schon keine Bedeutung mehr.</p> <p>In den gegenwärtigen Zeiten unvorhersehbarer Ereignisse ist es für Firmen wichtiger denn je, sich diesen Herausforderungen flexibel zu stellen um weiterhin handlungsfähig zu bleiben.</p> <p>Ein Umdenken ist vor allem im Bereich der Zusammenarbeit nötig. Agilität und Flexibilität, Virtualisierung und Digitalisierung sind jetzt nicht nur viele Firmen sondern auch für den Bereich Aus- und Weiterbildung existenziell. Wir haben daher unsere Projektmanagement Trainings auf online Trainings erweitert um Ihnen die Möglichkeit zu bieten auch in Zeiten von (verordnetem) Home Office an Aus- und Weiterbildungen teilzunehmen. Wie auch in den klassischen Präsenztrainings liegt in unseren online Trainings neben der Wissensvermittlung ein starker Fokus auf Zusammenarbeit und Interaktion zwischen den Teilnehmern um somit den bestmöglichen Mehrwert der Trainings für Sie zu generieren.</p> <p>Die Nachfrage nach Trainings in agilen Methoden ist daher hoch. Wir stellen Ihnen mit unserem Kooperationspartner CPS Consulting &amp; Projektmanagement unser 3Pworx Trainingsprogramm im Bereich klassisches/hybrides und agilen Projektmanagement genauer vor.</p> <p>21:30 Uhr: Q&amp;A</p> <p>Ca. 22:00 Uhr – Ende des 3Pworx 2. Agilen Trendforums Mai 2020 digital</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1584944740000,
      duration: 3600000,
      id: '269596936',
      name: 'AUS!Zeit - ja! oder?',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592641800000,
      local_date: '2020-06-20',
      local_time: '10:30',
      updated: 1584944740000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      is_online_event: false,
      group: {
        created: 1562082325000,
        name: 'Social Sabbatical - Mehr als eine Auszeit',
        id: 32306215,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Social-Sabbatical',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munchen-Social-Sabbatical/events/269596936/',
      description: '<p>Ob Persönlichkeitsentwicklung, spirituelle Erfahrung, sinnvolle Tätigkeit oder einfach mal raus aus dem Alltag zur Klärung der eigenen berufliche Situation – die Gründe für eine Auszeit sind vielfältig.</p> <p>Viele tragen den Gedanken an eine berufliche Auszeit schon lange mit sich herum und finden keine abschließende Entscheidung dafür oder dagegen. Andere entscheiden sich nach kürzester Zeit für ein Sabbatical. Woran liegt das? Und wie kommst du zu einer für dich passenden Entscheidung?</p> <p>Und auch diejenigen, die sich bereits entschieden haben, sollten sich im Vorfeld ein paar Fragen beantworten, während der Auszeit ein paar Hilfsmittel nutzen und für die Rückkehr einen Plan haben, um den größtmöglichen Nutzen aus der eigenen Auszeit zu ziehen.</p> <p>** Für wen ist das Webinar? **<br/>Für alle, die sich noch nicht sicher sind, ob sie eine Auszeit nehmen wollen und wie sie diese gestalten sollen.<br/>Für alle, die ihre Auszeit nutzen wollen, um sich beruflich nur zu orientieren.</p> <p>** Wer sind deine Begleiterin im Webinar? **<br/>Elke Dieterich, Gründerin von Manager für Menschen. Eigene Auszeit-Erfahrungen. Berät und motiviert seit 8 Jahren Menschen, die einen Auszeit-Wunsch haben und begleitet sie in der Umsetzung.<br/>Mehr Informationen unter www.managerfuermenschen.com .</p> <p>Christiane Karsch, Coach für berufliche Neuorientierung. Eigene Auszeiterfahrung<br/>Mehr Informationen unter www.berufliche-neuorientierung.net</p> <p>Wie melde ich mich an?<br/>Das Webinar findet über Zoom statt. Bitte registriere dich über folgenden Link.<br/> <p>Ich freue mich auf dich!<br/>Schöne Grüße<br/>Elke</p> <p>Technische Ausstattung:<br/>stabile Internet-Verbindung, externes Mikro, WebCam, Prozessor mind. 2Ghz oder höher (i3/i5/i7)<br/>Weitere Technische Infos gibt es hier (in aller Regel klappt es immer gut!):<br/><p>Vorabinfos zu zoom:<br/>Sobald ihr den Link zum Webinarraum bekommt, und diesen idealerweise am Tag vor dem Webinar anklickt, installiert sich ein kleines zoom Programm. Bei allen zukünftigen Aufrufen braucht dann nichts mehr gemacht zu werden, außer natürlich man verwendet dann einen anderen Computer.</p> <p>Ideal ist die Nutzung von google Chrome. Bitte stöpsle VOR Betreten des Raumes das Headset und ggfls. Kamera ein.</p> <p>Vor Webinar-Beginn gelangen alle zunächst in einen Warteraum und ich werde alle mit Beginn in den Webinarraum einlassen - erst dann ist man hör- und sichtbar.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1584390889000,
      duration: 14400000,
      id: '269466550',
      name: '3. agiles PM-Trendforum 2020 (digital) am 25.06.2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593100800000,
      local_date: '2020-06-25',
      local_time: '18:00',
      updated: 1587540743000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 39,
      is_online_event: false,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466550/',
      description: '<p>MS-Teams Meeting (Link):</p> <p> <p>Agenda:</p> <p>18:00 Uhr – Begrüßung, Einleitung, Infos zum Ablauf</p> <p>18:15 Uhr – Vortrag 1: -&gt; „Office 365 –Professionelles Arbeiten im Homeoffice: Wie können die Office 365 und Edison 365 Apps ideal für das Arbeiten im Homeoffice genutzt werden? – Digitaler Arbeitsplatz der Zukunft in Corona Zeiten</p> <p>Vortrag Herr Andreas Hock, Partner 3Pworx GmbH</p>',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1582538359000,
      duration: 10800000,
      id: '268947102',
      name: 'get Kanban Spiel + Open Space',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1589905800000,
      local_date: '2020-05-19',
      local_time: '18:30',
      updated: 1582538723000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 34,
      venue: {
        id: 25772139,
        name: 'it-agile GmbH München',
        lat: 48.1500244140625,
        lon: 11.546462059020996,
        repinned: true,
        address_1: 'Nyphenburgerstraße 86',
        address_2: '80636',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1520863131000,
        name: 'Kanban Community München - Der alternative Weg zu Agile',
        id: 27806088,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Kanban-Community-Munchen',
        who: 'Kanbunnys',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Kanban-Community-Munchen/events/268947102/',
      description: '<p>Hallo liebe Kanbunnys,</p> <p>es ist wieder soweit: wir Kanbunnys treffen uns. Wir machen wieder einen Open Space und für Leute die Lust haben, gibt es die Möglichkeit getKanban zu spielen. Es ist eine Simulation die Limitierung von Arbeit, Priorisieren, gemeinsam Entscheiden, tracken von Metriken spielerisch vermittelt. Wir entscheiden zu Beginn des Open Space wer getKanban spielen will. Die Voraussetzung ist, dass sich mindestens 4 Leute finden die die ganze Zeit dabei sind.</p> <p>Neben getKanban habt ihr im Rahmen des Open Space die Möglichkeit eure eigenen Themen und Fragen zu platzieren.</p> <p>Ist es für Dich das erste Mal bei der Kanban Community: komm einfach vorbei, höre zu, bring Dich ein, wo du willst, und hab Spaß :)</p> <p>Für Pizza und Bier (natürlich auch Softdrinks) ist ab 18:30 gesorgt.</p> <p>Viele Grüße<br/>Sebastian, Chris und Oliver</p> ',
      how_to_find_us: 'Die Büros von it-agile befinden sich im Hinterhof (an Stylight vorbei), Hauseingang ist bei einem Durchgang. Treppenhaus 3. 1. OG.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1587584223000,
      duration: 3600000,
      id: 'hxsrrrybcgblc',
      name: '(Un-)Glaubliches München - erste Online Stadtführung',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588096800000,
      local_date: '2020-04-28',
      local_time: '20:00',
      updated: 1587584223000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1583910278000,
        name: 'Die München Entdecker',
        id: 33538673,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Lebenszeit-Events',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Lebenszeit-Events/events/hxsrrrybcgblc/',
      description: '<p>Erste Online-Stadtführung Münchens</p> <p>Wir zeigen dir das (un-) glaubliche München ganz bequem und coronasicher von Zuhause aus.<br/>Du bist ausgangsbeschränkt und würdest gerne mal wieder was erleben? Dann nimm kostenfrei an unserer live moderierten Online- Führung teil.<br/>Du wirst unbekannte, kuriose, spektakuläre und witzige Geschichten über München hören, die dich direkt vom Couchsessel hauen!<br/>Der Clou dabei ist: ein Teil der Geschichten ist wahr, ein Teil nicht. Wer am besten rät, gewinnt einen (un-)glaublichen Preis!</p> <p>Termine:<br/>26.04. um 20 Uhr<br/>28.04. um 20 Uhr<br/>30.04. um 20 Uhr</p> <p>Dauer: ca. 45 Minuten</p> <p>--- Melde dich im Vorfeld kurz mit einer Nachricht bei uns und teile uns deine Email-Adresse mit. An diese Email schicken wir dir den Zugangslink. Es gibt limitierte Plätze! ---</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1574974419000,
      duration: 10800000,
      fee: {
        accepts: 'paypal',
        amount: 15,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: true,
      },
      id: '266812858',
      name: 'Agile Game Night #40 - Agile Fluency Game',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1589473800000,
      local_date: '2020-05-14',
      local_time: '18:30',
      updated: 1583918231000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      is_online_event: false,
      group: {
        created: 1471362725000,
        name: 'Agile Game Nights',
        id: 20321716,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Agile-Game-Night',
        who: 'Agile Gamer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Agile-Game-Night/events/266812858/',
      description: '<p>Save the Date! Florian Halmburger und weitere Spielleiter werden uns das Agile Fluency Game vorstellen.<br/>Für die Agile Game Night<br/>– Die Beschreibung zum Spiel / der Simulation / dem Thema kommt in Kürze...</p> <p>Das hier sind schon mal die vorläufigen Termine für die zweite Jahreshälfte:<br/>Q3: DO,[masked] + DI,[masked] - DO,[masked]<br/>Q4: DI,[masked] + DO,[masked] + DI,[masked]</p> <p>Du hast ein tolles Spiel und möchtest uns das gern zeigen oder auch ein neues ausprobieren? Gastmoderatoren sind herzlich eingeladen. Sprich uns an.</p> <p>Happy Gaming<br/>Ellen und Sieglinde</p> <p>PS: Du hast auch ein tolles Spiel und möchtest uns das gern zeigen oder auch ausprobieren? Gastmoderatoren sind herzlich eingeladen. Sprich uns an.<br/>----------------------------<br/>Die Agile Game Night ist die Experimentierplattform für Business-Spiele</p> <p>Alle Übungen und Spiele können in Trainings, Workshops, aber auch Scrum-Retrospektiven oder anderen agilen Meetings genutzt werden, im Team neue Lösungsansätze zu entwickeln und Erfahrungen erlebbar zu machen. Unsere Game Night ist für jeden gedacht, der mehr über Agile Methoden erfahren und dabei Spaß haben und spielen möchte. Darüber hinaus können auch Trainer und Coaches davon profitieren, wie sie Spiele in ihre Seminare einbinden und diese vorab schon mal ausprobieren können.</p> <p>Spiele bilden metaphorisch reales Leben ab und helfen, Strukturen nicht nur theoretisch, sondern persönlich zu erleben, erfahren und verinnerlichen.</p> <p>Teilen Sie die Veranstaltung und laden Sie andere ein:</p> <p>',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
}
export { mockEvents };